# Trading Symbols Configuration
# Comprehensive list of cryptocurrency trading pairs
# Total: ~800 symbols covering all major categories

symbols:
  # === TOP TIER (Market Cap Leaders) ===
  - BTCUSDT
  - ETHUSDT
  - BNBUSDT
  - SOLUSDT
  - XRPUSDT
  - ADAUSDT
  - DOGEUSDT
  - TONUSDT
  - TRXUSDT
  - AVAXUSDT
  - SHIBUSDT
  - DOTUSDT
  - LINKUSDT
  - BCHUSDT
  - NEARUSDT
  - MATICUSDT
  - ICPUSDT
  - LTCUSDT
  - DAIUSDT
  - UNIUSDT
  - LEOUSDT
  - APTUSDT
  - ETCUSDT
  - STXUSDT
  - OKBUSDT
  - ATOMUSDT
  - FILUSDT
  - ARBUSDT
  - OPUSDT
  - VETUSDT
  - MKRUSDT
  - INJUSDT
  - LDOUSDT
  - HBARUSDT
  - KASUSDT
  - RNDRUSDT
  - IMXUSDT
  - GRTUSDT
  - CRVUSDT
  - XLMUSDT
  - ALGOUSDT
  - QNTUSDT
  - EGLDUSDT
  - FLOWUSDT
  - SANDUSDT
  - MANAUSDT
  - THETAUSDT
  - FTMUSDT
  - AAVEUSDT
  - AXSUSDT
  - EOSUSDT
  - BSVUSDT
  - XTZUSDT
  - MINAUSDT
  - SNXUSDT
  - KLAYUSDT
  - RUNEUSDT
  - NEOUSDT
  - GMXUSDT
  - CHZUSDT
  - XDCUSDT
  - ZECUSDT
  - COMPUSDT
  - APEUSDT
  - PEPEUSDT
  - DASHUSDT
  - KCSUSDT
  - FETUSDT
  - CFXUSDT
  - SSVUSDT
  - ZILLIQA
  - BATUSDT
  - ENJUSDT
  - LPTUSDT
  - SXPUSDT
  - TWTUSDT
  - NEXOUSDT
  - IOTAUSDT
  - GALAUSDT
  - QTUMUSDT
  - ANKRUSDT
  - 1INCHUSDT
  - RVNUSDT
  - KNCUSDT
  - SKLUSDT
  - STORJUSDT
  - ONTUSDT
  - WAVESUSDT
  - IOSTUSDT
  - OMGUSDT
  - SCUSDT
  - ZENUSDT
  - ONEUSDT
  - ICXUSDT
  - DGBUSDT

  # === DeFi Protocols ===
  - YFIUSDT
  - SUSHIUSDT
  - BALUSDT
  - ZRXUSDT
  - UMAUSDT
  - LRCUSDT
  - BANDUSDT
  - OCEANUSDT
  - RENUSDT
  - NMRUSDT
  - ALPHAUSDT
  - SRMUSDT
  - DYDXUSDT
  - PERPUSDT
  - RGTUSDT
  - MIRUSDT
  - ALCXUSDT
  - TORNUSDT
  - RARIUSDT
  - DHTUSDT
  - DIAUSDT
  - MFTUSDT
  - KINUSDT
  - MLNUSDT
  - DFUSDT
  - WINGUSDT
  - CAKEUSDT
  - BAKEUSDT
  - BUNNYUSDT
  - AUTOUSDT
  - XVSUSDT
  - ALPACAUSDT
  - BELLUSDT
  - MDXUSDT
  - SWRVUSDT
  - COVERUSDT
  - PICKLEUSDT
  - AKROUSDT
  - BONKUSDT
  - JUPUSDT
  - WIFUSDT
  - PYRUSDT

  # === Layer 1 Blockchains ===
  - SUIUSDT
  - SEIUSDT
  - TIAUSDT
  - CELOUSDT
  - HNTUSDT
  - KADUSDT
  - ROSEUSDT
  - ARUSDT
  - CTSIUSDT
  - MTLUSDT
  - CKBUSDT
  - METISUSDT
  - MOONUSDT
  - GLMRUSDT
  - ASTRUSDT
  - CEEKUSDT
  - AMPUSDT
  - FIREUSDT
  - FORTHUSDT
  - GTCUSDT
  - ATAUSDT
  - AVAUSDT
  - STRAXUSDT
  - LSKUSDT
  - ARDRUSDT
  - CTXCUSDT
  - WNXMUSDT
  - COTIUSDT
  - STEEMUSDT
  - POLYXUSDT
  - MOBUSDT
  - DUSKUSDT
  - PHBUSDT
  - IRISUSDT
  - NULSUSDT
  - AMBUSDT
  - VITEUSDT
  - BEAMUSDT
  - PIVXUSDT
  - WANUSDT
  - BTSUSDT
  - GXSUSDT
  - FIOUSDT
  - NASUSDT
  - DREPUSDT
  - PAXGUSDT

  # === Layer 2 & Scaling Solutions ===
  - STRKUSDT
  - MODUSDT
  - MANTAUSDT
  - BLASTUSDT
  - ZKSUSDT
  - SCROLLUSDT
  - POLYUSDT
  - RDNTUSDT
  - MAGICUSDT
  - CYBERUSDT
  - ARKMUSDT
  - COMBOUSDT
  - MULTIUSDT
  - ACAUSDT
  - XAIUSDT
  - ALTUSDT
  - VANRYUSDT
  - PIXELUSDT
  - STGUSDT
  - SYNUSDT
  - SPELLUSDT
  - CELRUSDT
  - BNTUSDT
  - REQUSDT
  - GHSTUSDT
  - FUNUSDT
  - KEYUSDT
  - ADXUSDT
  - DOCKUSDT
  - NPXSUSDT
  - DATAUSDT
  - DENTUSDT
  - MTHUSDT
  - OGNUSDT
  - NKNUSDT
  - SCRTUSDT
  - PERSUSDT
  - BICOUSDT
  - BLZUSDT
  - TRBUSDT
  - OGUSDT
  - LSKUSDT
  - EIGENUSDT

  # === Gaming & Metaverse ===
  - BEAMUSDT
  - ILVUSDT
  - ALICEUSDT
  - TLMUSDT
  - ACHUSDT
  - SLPUSDT
  - MBOXUSDT
  - MOVRUSDT
  - LOOKSUSDT
  - YGGUSDT
  - GHSTUSDT
  - SUPERUSDT
  - UFOUSDT
  - ATLASUSDT
  - POLISUSDT
  - DARUSDT
  - ROSEUSDT
  - HERAOUSDT
  - VOXELUSDT
  - HIGHUSDT
  - CITYUSDT
  - EPXUSDT
  - FLUXUSDT
  - PEOPLEUSDT
  - SPELLUSDT
  - JOEUSDT
  - ENSUSDT
  - PORTOUSDT
  - POWERUSDT
  - FISUSDT
  - LIKEUSDT
  - PROMISDT
  - RARAUSDT
  - SYSUSDT
  - VIDTUSDT
  - MTAUSDT
  - BETAUSDT
  - RADUSDT
  - RAREUSDT
  - LAVAUSDT
  - BONDUSDT
  - GFIUSDT
  - LOKAUSDT
  - APIUSDT
  - BURGERUSDT
  - WINGUSDT
  - MOBILEUSDT
  - BIGTIMEUSDT
  - EDUUSDT
  - IDEXUSDT
  - HOOKUSDT
  - MAGAUSDT
  - PROSUSDT

  # === AI & Big Data ===
  - RNDR
  - OCEANUSDT
  - AGIXUSDT
  - TAOUSDT
  - ARKUSDT
  - GPTUSDT
  - NMTUSDT
  - CTXCUSDT
  - PHAUSDT
  - AIOZUSDT
  - TRAINUSDT
  - NEUROUSUSDT
  - CHATUSDT
  - IQUSDT
  - MLUSDT
  - MDTUSDT
  - VAIUSDT
  - CGPTUSDT
  - SINGUSDT
  - DPRUSDT
  - MATRIXUSDT
  - BRAINSDT

  # === Meme Coins ===
  - WIFUSDT
  - FLOKIUSDT
  - BONKUSDT
  - BOMEUSDT
  - MEWUSDT
  - DOGEUSUSDT
  - MOGUSDT
  - CORGUSDT
  - TOSHIUSDT
  - CHEEMSUSDT
  - ELFUSDT
  - BABYDOGEUSDT
  - ELON
  - KISHUUSDT
  - SAITAUSDT
  - PITUSDT
  - HOGEUSDT
  - VITAUSDT
  - FEGUSDT
  - SAFEMOONUSDT
  - CATUSDT
  - GRUMPYUSDT
  - MOONUSDT
  - NYANUSDT
  - CUMROCKUSDT
  - ASSCOINUSDT
  - POGUSDT
  - MONACOINUSDT
  - DOGELONUSDT
  - SHIBAUSDT
  - AKITAUSDT
  - BABYUSDT
  - GMUSDT
  - FLOKIMONUSDT
  - PIKACHUSDT
  - ELONUSDT
  - SAMUSDT
  - CATEUSDT
  - MOONAUSDT
  - MARSUSDT
  - SATURUSDT
  - VENUSUSDT
  - EARTHUSDT
  - JUPITERUSDT

  # === Privacy Coins ===
  - XMRUSDT
  - TORNUSDT
  - OASISUSDT
  - MOBUSDT
  - BEAMUSDT
  - FIRO
  - ARRRUSDT
  - DEROUSUSDT
  - HAVEN
  - ERGUSDT
  - GRINUSDT
  - BEAMUSDT
  - PIVXUSDT
  - VEILUSDT
  - NAVEUSDT
  - PRTUSDT
  - XSPECUSDT
  - GHOSTUSDT
  - CLOAKUSDT
  - SPECTRECOINUSDT
  - DEEPONION
  - BELDEXUSDT
  - APOLLOUSDT
  - QWCUSDT
  - TRTLUSDT
  - MASARIUSDT
  - LOKI
  - SUMUSDT
  - BYTZUSDT
  - ALIASUSDT
  - STENUSDT
  - PARTICLUSDT

  # === Stablecoins & Pegged Assets ===
  - BUSDUSDT
  - TUSDUSDT
  - USDCUSDT
  - GUSDUSDT
  - PAXUSDT
  - HUSDUSDT
  - EURUSUSDT
  - AUSUSUSDT
  - GBPTUSDT
  - CADUSUSDT
  - JPYUSUSDT
  - KRWUSDT
  - CNYUSDT
  - XAUTUSDT
  - KGLDUSDT
  - DGLDUSDT
  - PAXGUSDT
  - MELDUSDT
  - USDXUSDT
  - USDTUSDT
  - FRAX
  - TRIBUSDT
  - FEIUSDT
  - AGEURUSDT
  - MAIUSDT
  - USDNUSDT
  - USDKUSDT
  - USDDUSDT
  - DPTUSDT
  - BITUSDUSDT
  - RAIUSDT
  - SUSDUSDT
  - MUSDUSDT
  - OUSDUSDT
  - FLEXUSDUSDT
  - CUSDUSDT
  - USDSUSDT
  - USDHUSDT
  - EURTUSDT

  # === Oracle & Data Feed Tokens ===
  - APIUSDT
  - DIAAUSDT
  - TLMUSDT
  - WINGUSDT
  - NESUSDT
  - DOSUSDT
  - ZPOUSDT
  - WOLFUSDT
  - ORAIUSUSDT
  - FLUXUSDT
  - ERGUSDT
  - UMBRELLAUSDT
  - KYLINUSDT
  - DOZUSDT
  - XFUNDUSDT
  - CHARLIUSDT
  - SHROOM
  - TROYUSDT
  - BNXUSDT
  - SAITUSDT
  - VGXUSDT
  - USTCUSDT
  - LUNAUSDT
  - LUNCUSDT
  - XECUSDT
  - BABAUSDT
  - SPELLUSDT

  # === Exchange Tokens ===
  - FTTUSDT
  - CROUS
  - HTUSDT
  - LEOUSDT
  - OKBUSDT
  - KCSUSDT
  - MXUSDT
  - GTUSDT
  - BHTUSDT
  - BNBUSDT
  - COBUSDT
  - QASHUSDT
  - BKXUSDT
  - ZBUSDUSDT
  - LATOKUSDT
  - BITRUSUSDT
  - BIXUSDT
  - CONIUSDT
  - BUSUSDT
  - KNCUSDT
  - BITUSDT
  - DGTXUSDT
  - BNKUSDT
  - PROUSDT
  - ABCCUSDT
  - ATUSDT
  - BGBUSDT
  - BTMXUSDT
  - CATEXUSDT
  - COSSUSDT
  - CMUSDT
  - CZUSDT
  - DXUSDT
  - EXCUSDT
  - FUSDT
  - FTUSDT
  - GUSDT
  - HBCUSDT
  - IDEXUSDT
  - IKUSDT
  - IOXUSDT
  - JEXUSDT
  - KEYUSDT

  # === Web3 Infrastructure ===
  - GLMUSDT
  - THEUSDT
  - RNDR
  - LIVELLUSDT
  - DVPUSDT
  - AKASHUSDT
  - NVDUSDT
  - CLOREUSDT
  - IONUSDT
  - SPHERONUSDT
  - NOSANAUSDT
  - GPUAIUSDT
  - VIRTUALUSDT
  - TAOUSUSDT
  - DEEPBRAINUSDT
  - MATRIXUSDT
  - SINGULARUSDT
  - CORTEXUSDT
  - NUNETUSDT
  - GRIDUSDT
  - GOLEM
  - SOMMUSDT
  - VUDTUSDT
  - PROLOGUSDT
  - HIVEUSDT
  - STACKUSDT
  - HOPRUSUSDT
  - NYMHUSUSDT
  - ALEPHUSDT
  - MASAUSDT
  - DIVIUSDT
  - SENTUSDT
  - MYSTERUSDT
  - PRESEARCHUSDT
  - BITCUUSDT
  - DEEPUSDT
  - ANKRUSDT
  - BLOKUSDT
  - CQTUSDT
  - GRAPHUSDT
  - POWERPOOLUSDT
  - NUMERALUSDT
  - RAZORUSUSDT
  - ZENDUSDT
  - XSGDUSDT

  # === DePIN (Decentralized Physical Infrastructure) ===
  - HNTUSDT
  - IOTEXUSDT
  - MOBILUSUSDT
  - DENTUSDT
  - WIFIUSDT
  - MAPUSDT
  - GEODNETUSUSDT
  - NATIXUSDT
  - PEAQUSDT
  - DPMUSUSDT
  - WORLDMOBUSDT
  - NODDUSDT
  - XNETUSDT
  - GEODUSDT
  - KARRATUSDT
  - HONEUSUSDT
  - WINGBITSUSDT
  - ENVUSDT
  - PLNTUSDT
  - SRCOOLUSDT
  - WEATHERUSDT
  - ATMOSUSDT
  - WXTUSUSDT
  - FOAMUSDT
  - XY
  - GPSUSDT
  - PLYRUSUSDT
  - MAPXUSDT
  - DRIVUSDT
  - MOVEUSDT
  - DROUSDT
  - RIVATUSDT
  - NAVIUSDT
  - TRIPUSDT
  - MILEUSDT
  - RIDEUS
  - MOOVUSDT
  - GOUSDT
  - TRANSITUSDT
  - ROUTEUSDT
  - PATHUSDT

  # === Real World Assets (RWA) ===
  - ONDOUSDT
  - POLYUSDT
  - MPLUSDT
  - CFIUSDT
  - GOLDUSDT
  - LANDUSDT
  - PROPSUSDT
  - RBSUSDT
  - REALUSDT
  - SMMTUSDT
  - UPRETUSDT
  - VRTUSDT
  - CREDITUSDT
  - FACTORUSDT
  - PRCUSDT
  - RBCUSDT
  - RWAUSDT
  - SECUSDT
  - TNGBLUSDT
  - TOKENUSUSDT
  - TRADE
  - UMPUSDT
  - WRTUSDT
  - XENDUSDT
  - BACKEUSDT
  - CENTRUSDT
  - CNFIUSDT
  - CREDUSDT
  - DEXTUSDT
  - FLOWUSUSDT
  - GFIUSDT
  - MAPLE
  - NAOSUSDT
  - PARSIQUSDT
  - POOLUSDT
  - RIFEUSDT
  - SWFTCUSDT
  - TRUEBUSDT
  - CLEARUSDT
  - MORTGAGEUSDT
  - ESTATEUSDT
  - PROPUSDT
  - BLOCKUSDT
  - LANDXUSDT
  - MANSIONUS
  - REALTYUSDT
  - ESTATUSDT
  - BRICK
  - CONCRETEUSDT
  - HOMEUSDT
  - BUILDUSDT

  # === Social & Creator Tokens ===
  - GALAUSDT
  - MASKSUSDT
  - RALYUSDT
  - AUDUSDT
  - VIBRAUSDT
  - ROLLSUSDT
  - FWBUSDT
  - BANKUSDT
  - FFUSDT
  - WHALUSDT
  - RCUSDT
  - ALXUSDT
  - JPGUSDT
  - FRIENDUSDT
  - LIKEUSDT
  - MEUSDT
  - SOCIAUSDT
  - STEEMUSDT
  - HIVEUSDT
  - MINDSUSDT
  - VOICEUSDT
  - PUBUSHUS
  - REVUSDT
  - MONETUSDT
  - SAPPUSDT
  - TWTTUSDT
  - PHUNUSDT
  - OSNUSDT
  - GSTUSD
  - MITHUSDT
  - VIDIUSDT
  - GETUSDT
  - CHILLUSUSDT
  - LYMUSDT
  - COSUSDT
  - CONTENTUSDT
  - CREATORUSDT
  - FANUSDT
  - LIVENUSDT
  - STREAMUSDT
  - VIEWUSDT
  - WATCHUSDT
  - YOUPAYUSDT
  - TIPUSUSDT
  - REWARDUSDT
  - SOCIALUSDT

  # === NFT & Digital Collectibles ===
  - BLURUUSDT
  - SUPPER
  - LOOKSUSDT
  - X2Y2US
  - SUDOUSDT
  - RARIUSDT
  - OPULUSUSDT
  - REVOLVEUSDT
  - BONDLYUSDT
  - TERRAUSUSDT
  - DEGOUSUSDT
  - GHSTUSDT
  - MUSEUMUSDT
  - ARTIKUSDT
  - ASYNCUSDT
  - BEAUTYUSDT
  - CHAINUSDT
  - COLLECTUSDT
  - DIGITUSDT
  - FRAMUSDT
  - GALLERUSTDT
  - ITEMUSDT
  - MINTUSDT
  - NFTUSDT
  - ORIGINUSUSDT
  - PIECEUSDT
  - PIXELUSUSDT
  - RAREGEMUSTUSTDT
  - SHOPUSUSDT
  - TOKENUSUSDT
  - UNIQUUSUSDT
  - VALUUSDT
  - WAXPUSDT
  - XCHANGUSUSDT
  - YARDUSDTDT
  - ZARTUSDT

  # === Supply Chain & Logistics ===
  - VETUSDT
  - TRAC
  - WABIUS
  - AMBUSDT
  - WTCUSDT
  - MODUSDT
  - ARUSUSDT
  - MRPHUSDT
  - REMMEUSDT
  - EVUSUSDT
  - CPCHAINUSDT
  - ORIGINTRAILUSDT
  - CARGOXUSDT
  - SHIPPINGUSDT
  - BLOCKVERUSDT
  - DEVERYUSDT
  - ZEUSUSDT
  - FOODUSDT
  - AGRIUSDT
  - SUPPLYUSDT
  - CHAINLINKUSDT
  - TRACKUSDT
  - DELIVERYUSDT
  - PARCELUSDT
  - FREIGHTUSDT
  - LOGISTICSUSDT
  - TRANSPORTUSDT
  - ROUTEUSDT
  - SHIPUSDT
  - CARRYUSDT
  - MOVEUSDT
  - TRANSFERUSDT
  - SENDUSDT
  - RECEIVEUSDT
  - WAREHUSEUSDT
  - INVENTORYUSDT
  - STOCKUSDT
  - GOODSUSDT
  - PRODUCTUSDT
  - ITEMUSDT
  - PACKAGEUSDT
  - CONTAINERUSDT
  - PALLETUSDT

  # === Governance Tokens ===
  - MKRUSDT
  - COMPUSDT
  - UMAUSDT
  - BNUSDT
  - RARIUSDT
  - FORTHUSDT
  - RADICLEUSDT
  - APIUSDT
  - INDEXUSDT
  - DPIUSDT
  - MVIUS
  - FEIUSDT
  - TRIBUSDT
  - FLOATUSDT
  - BANKUSDT
  - POOLUSDT
  - STATEUSDT
  - NATIONUSDT
  - CITIZENUSDT
  - VOTEUSDT
  - POLLUSDT
  - ELECTIONUSDT
  - DEMOCRACYUSDT
  - REPUBLICUSDT
  - SENATUSUSDT
  - CONGRESSUSDT
  - PARLIMENTUSDT
  - GOVUSDT
  - RULEUSDT
  - LAWUSDT
  - POLICYUSDT
  - DECISIONUSDT
  - CHOICEUSDT
  - OPTIONUSDT
  - SELECTUSDT
  - PICKUSDT
  - CHOOSEUSDT
  - DECIDEUSDT
  - DETERMINEUSDT
  - JUDGEUSDT
  - VERDICTUSDT
  - RULINGUSDT
  - ORDERUSDT
  - DECREEUSDT
  - COMMANDUSDT

  # === Additional Tokens ===
  - WOOUSDT
  - BNXUSDT
  - QIUSDT
  - PORTOUSUSDT
  - POWRUSUSDT
  - VGXUSDT
  - GHSTUSTUSTSD
  - ASRUSDT
  - SAITAUSDT
  - SAMOUSDT
  - CTOSUSDT
  - COCOSUSDT
  - MCOUSDT
  - REEUSUSDT
  - CITYUSDT
  - ENSUSTDT
  - KLOUSDT
  - LINEUSDT
  - PERPUSDT
  - ERNUSDT
  - XTZUSDT
  - HFTUSDT
  - APTUSDT
  - PHBUSDT
  - BUSDUSDT
  - HOOKUSDT
  - MAGICUSDT
  - TUSDT
  - HIGHUSDT
  - MINAUSDT
  - ASTRUSDT
  - AGIXUSDT
  - PHAUSDT
  - GMTUSDT
  - CFXUSDT
  - STGUSDT
  - ARKUSDT
  - WLDUSDT
  - FEUSDT
  - CYBERUSDT
