package symbols

// DefaultSymbols is the curated list of USDT trading pairs to track
// This is the source of truth for all symbol operations
var DefaultSymbols = []string{
	"1INCHUSDT", "AAVEUSDT", "ADAUSDT", "ALCXUSDT", "ALICEUSDT", "ANKRUSDT", "APEUSDT", "ARBUSDT",
	"AUDIOUSDT", "AURORAUSDT", "AVAXUSDT", "AXSUSDT", "BATUSDT", "BLURUSDT", "BNBUSDT", "BOBAUSDT",
	"BONEUSDT", "BTCUSDT", "C98USDT", "CAKEUSDT", "CELOUSDT", "CHZUSDT", "COMPUSDT", "CRVUSDT",
	"CVXUSDT", "DOGEUSDT", "DOTUSDT", "DYDXUSDT", "ENJUSDT", "ETHUSDT", "FETUSDT", "FLOKIUSDT",
	"FXSUSDT", "GALAUSDT", "GLMRUSDT", "GMXUSDT", "GRTUSDT", "GTUSDT", "HOTUSDT", "ILVUSDT",
	"IMXUSDT", "INJUSDT", "IOTXUSDT", "JASMYUSDT", "KDAUSDT", "LDOUSDT", "LINKUSDT", "LOOKSUSDT",
	"LRCUSDT", "MAGICUSDT", "MANAUSDT", "MASKUSDT", "METISUSDT", "MINAUSDT", "MOVRUSDT", "NEXOUSDT",
	"OPUSDT", "PAXGUSDT", "PEPEUSDT", "POLSUSDT", "QNTUSDT", "RAYUSDT", "ROSEUSDT", "RPLUSDT",
	"RUNEUSDT", "SANDUSDT", "SFPUSDT", "SHIBUSDT", "SNXUSDT", "SOLUSDT", "SPELLUSDT", "STXUSDT",
	"SUSHIUSDT", "TFUELUSDT", "THETAUSDT", "TLMUSDT", "TRIBEUSDT", "TWTUSDT", "UNIUSDT", "WBTCUSDT",
	"WOOUSDT", "XCNUSDT", "XDCUSDT", "XRPUSDT", "XYOUSDT", "YFIUSDT", "ZRXUSDT",
}
